platform :ios, '8.0'
use_frameworks!

target ’SwiftSina’ do
	pod 'SwiftyJSON'
    pod 'Alamofire', '~> 4.4'
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'SnapKit', '~> 3.2.0'
    pod 'Kingfisher'
    
end
